// src/lib/lang.js
export const translations = {
  id: {
    // Nav
    logout: 'Keluar', loading: 'Memuat data...',
    // Buttons
    add: '+ Tambah', edit: 'Edit', save: 'Simpan', saving: 'Menyimpan...',
    cancel: 'Batal', update: 'Update', updating: 'Menyimpan...',
    delete: 'Ya, Hapus', deleting: 'Menghapus...',
    refresh: '↻ Refresh',
    // Common
    total: 'Total', noData: 'Belum ada data',
    notes: 'Catatan', optional: 'Opsional', category: 'Kategori',
    confirmDeleteTitle: 'Hapus item ini?', confirmDeleteSub: 'Tindakan ini tidak dapat dibatalkan.',
    // Summary
    portfolioSummary: 'Ringkasan Portofolio', totalAsset: 'Total Aset',
    target: 'Target', fromTarget: 'dari target',
    liquidAsset: 'Aset Liquid', nonLiquidAsset: 'Aset Tidak Liquid',
    physicalAsset: 'Aset Fisik', assetAllocation: 'Alokasi Aset',
    nonLiquid: 'Tidak Liquid', liquid: 'Liquid', physical: 'Fisik',
    totalBuyPrice: 'Total Nilai Beli', items: 'item', positions: 'pos',
    // Bibit
    bibitTitle: 'BIBIT — Reksa Dana & Obligasi',
    addBibit: 'Tambah Aset BIBIT', editBibit: 'Edit Aset BIBIT',
    assetName: 'Nama Aset', balance: 'Saldo', balanceLabel: 'Saldo (Modal)',
    actual: 'Aktual', actualLabel: 'Aktual (Sekarang)', pnl: 'PnL',
    profitRank: 'Top Profit', topProfitSub: 'Ranking berdasarkan % keuntungan tertinggi',
    // Binance
    binanceTitle: 'Binance — Crypto Portfolio',
    addCrypto: 'Tambah Crypto', editCrypto: 'Edit Crypto',
    symbol: 'Symbol', balanceIdr: 'Saldo (IDR)', actualIdr: 'Aktual (IDR)',
    actualUsdt: 'Aktual (USDT)', currentRate: 'Rate saat ini',
    loadingRate: 'Memuat...', updatedAt: 'diperbarui',
    balanceUsdt: 'Saldo Modal (USDT)', actualNowUsdt: 'Aktual Sekarang (USDT)',
    // Physical
    physicalTitle: 'Aset Fisik', addPhysical: 'Tambah Aset Fisik', editPhysical: 'Edit Aset Fisik',
    buyPrice: 'Harga Beli', buyDate: 'Tgl Beli', age: 'Umur', pricePerMonth: 'Harga/Bulan',
    efficiencyRank: 'Ranking Efisiensi', lowestCostSub: 'Harga/bulan terendah = paling efisien',
    addDateHint: 'Tambah tanggal beli\nuntuk melihat ranking',
    // Liquid
    liquidTitle: 'Aset Liquid', addLiquid: 'Tambah Aset Liquid', editLiquid: 'Edit Aset Liquid',
    name: 'Nama', nameHint: 'Nama / Keterangan', amount: 'Jumlah', totalCash: 'Total Kas',
    jhtTitle: 'JHT — BPJS Ketenagakerjaan', jhtSub: 'Update manual setiap ada perubahan saldo',
    // Categories
    pasar_uang: 'Pasar Uang', obligasi: 'Obligasi', saham: 'Saham',
    main_pocket: 'Main Pocket', dana_darurat: 'Dana Darurat', lainnya: 'Lainnya',
    // Toast
    toastSaved: 'Berhasil disimpan', toastAdded: 'Berhasil ditambahkan',
    toastDeleted: 'Berhasil dihapus', toastUpdated: 'Berhasil diperbarui',
    // Validation
    errName: 'Nama aset tidak boleh kosong', errBalance: 'Saldo modal harus lebih dari 0',
    errActual: 'Nilai aktual tidak boleh negatif', errSymbol: 'Symbol tidak boleh kosong',
    errNoRate: 'Rate USDT/IDR belum tersedia. Klik Refresh rate dulu.',
    errSaldoUsdt: 'Saldo modal harus lebih dari 0 USDT',
    errAktualUsdt: 'Nilai aktual tidak boleh kosong atau negatif',
    errNama: 'Nama tidak boleh kosong', errJumlah: 'Jumlah harus lebih dari 0',
    errBuyPrice: 'Harga beli harus lebih dari 0', errJhtNeg: 'Jumlah tidak boleh negatif',
  },
  en: {
    logout: 'Logout', loading: 'Loading...',
    add: '+ Add', edit: 'Edit', save: 'Save', saving: 'Saving...',
    cancel: 'Cancel', update: 'Update', updating: 'Saving...',
    delete: 'Yes, Delete', deleting: 'Deleting...',
    refresh: '↻ Refresh',
    total: 'Total', noData: 'No data yet',
    notes: 'Notes', optional: 'Optional', category: 'Category',
    confirmDeleteTitle: 'Delete this item?', confirmDeleteSub: 'This action cannot be undone.',
    portfolioSummary: 'Portfolio Summary', totalAsset: 'Total Assets',
    target: 'Target', fromTarget: 'of target',
    liquidAsset: 'Liquid Assets', nonLiquidAsset: 'Non-Liquid Assets',
    physicalAsset: 'Physical Assets', assetAllocation: 'Asset Allocation',
    nonLiquid: 'Non-Liquid', liquid: 'Liquid', physical: 'Physical',
    totalBuyPrice: 'Total Purchase Value', items: 'items', positions: 'pos',
    bibitTitle: 'BIBIT — Mutual Funds & Bonds',
    addBibit: 'Add BIBIT Asset', editBibit: 'Edit BIBIT Asset',
    assetName: 'Asset Name', balance: 'Balance', balanceLabel: 'Balance (Principal)',
    actual: 'Current', actualLabel: 'Current Value', pnl: 'PnL',
    profitRank: 'Top Profit', topProfitSub: 'Ranked by highest % return',
    binanceTitle: 'Binance — Crypto Portfolio',
    addCrypto: 'Add Crypto', editCrypto: 'Edit Crypto',
    symbol: 'Symbol', balanceIdr: 'Balance (IDR)', actualIdr: 'Current (IDR)',
    actualUsdt: 'Current (USDT)', currentRate: 'Current rate',
    loadingRate: 'Loading...', updatedAt: 'updated',
    balanceUsdt: 'Balance (USDT)', actualNowUsdt: 'Current Value (USDT)',
    physicalTitle: 'Physical Assets', addPhysical: 'Add Physical Asset', editPhysical: 'Edit Physical Asset',
    buyPrice: 'Purchase Price', buyDate: 'Purchase Date', age: 'Age', pricePerMonth: 'Price/Month',
    efficiencyRank: 'Efficiency Ranking', lowestCostSub: 'Lowest price/month = most efficient',
    addDateHint: 'Add purchase date\nto see ranking',
    liquidTitle: 'Liquid Assets', addLiquid: 'Add Liquid Asset', editLiquid: 'Edit Liquid Asset',
    name: 'Name', nameHint: 'Name / Description', amount: 'Amount', totalCash: 'Total Cash',
    jhtTitle: 'JHT — Employment Insurance', jhtSub: 'Update manually when balance changes',
    pasar_uang: 'Money Market', obligasi: 'Bonds', saham: 'Stocks',
    main_pocket: 'Main Pocket', dana_darurat: 'Emergency Fund', lainnya: 'Others',
    toastSaved: 'Saved successfully', toastAdded: 'Added successfully',
    toastDeleted: 'Deleted successfully', toastUpdated: 'Updated successfully',
    errName: 'Asset name cannot be empty', errBalance: 'Balance must be greater than 0',
    errActual: 'Current value cannot be negative', errSymbol: 'Symbol cannot be empty',
    errNoRate: 'USDT/IDR rate not available. Click Refresh rate first.',
    errSaldoUsdt: 'Balance must be greater than 0 USDT',
    errAktualUsdt: 'Current value cannot be empty or negative',
    errNama: 'Name cannot be empty', errJumlah: 'Amount must be greater than 0',
    errBuyPrice: 'Purchase price must be greater than 0', errJhtNeg: 'Amount cannot be negative',
  }
}
