// src/lib/lang.js
export const translations = {
  id: {
    // Nav
    logout: 'Keluar', loading: 'Memuat data...',
    // Buttons
    add: '+ Tambah', edit: 'Edit', save: 'Simpan', saving: 'Menyimpan...',
    cancel: 'Batal', update: 'Update', updating: 'Menyimpan...',
    delete: 'Ya, Hapus', deleting: 'Menghapus...',
    refresh: '↻ Refresh',
    // Common
    total: 'Total', noData: 'Belum ada data',
    notes: 'Catatan', optional: 'Opsional', category: 'Kategori',
    confirmDeleteTitle: 'Hapus item ini?', confirmDeleteSub: 'Tindakan ini tidak dapat dibatalkan.',
    // Summary
    portfolioSummary: 'Ringkasan Portofolio', totalAsset: 'Total Aset',
    target: 'Target', fromTarget: 'dari target',
    liquidAsset: 'Aset Liquid', nonLiquidAsset: 'Aset Tidak Liquid',
    physicalAsset: 'Aset Fisik', assetAllocation: 'Alokasi Aset',
    nonLiquid: 'Tidak Liquid', liquid: 'Liquid', physical: 'Fisik',
    totalBuyPrice: 'Total Nilai Beli', items: 'item', positions: 'pos',
    // Bibit
    bibitTitle: 'BIBIT — Reksa Dana & Obligasi',
    addBibit: 'Tambah Aset BIBIT', editBibit: 'Edit Aset BIBIT',
    assetName: 'Nama Aset', balance: 'Saldo', balanceLabel: 'Saldo (Modal)',
    actual: 'Aktual', actualLabel: 'Aktual (Sekarang)', pnl: 'PnL',
    profitRank: 'Top Profit', topProfitSub: 'Ranking berdasarkan % keuntungan tertinggi',
    // Binance
    binanceTitle: 'Binance — Crypto Portfolio',
    addCrypto: 'Tambah Crypto', editCrypto: 'Edit Crypto',
    symbol: 'Symbol', balanceIdr: 'Saldo (IDR)', actualIdr: 'Aktual (IDR)',
    actualUsdt: 'Aktual (USDT)', currentRate: 'Rate saat ini',
    loadingRate: 'Memuat...', updatedAt: 'diperbarui',
    balanceUsdt: 'Saldo Modal (USDT)', actualNowUsdt: 'Aktual Sekarang (USDT)',
    // Physical
    physicalTitle: 'Aset Fisik', addPhysical: 'Tambah Aset Fisik', editPhysical: 'Edit Aset Fisik',
    buyPrice: 'Harga Beli', buyDate: 'Tgl Beli', age: 'Umur', pricePerMonth: 'Harga/Bulan',
    efficiencyRank: 'Ranking Efisiensi', lowestCostSub: 'Harga/bulan terendah = paling efisien',
    addDateHint: 'Tambah tanggal beli\nuntuk melihat ranking',
    // Liquid
    liquidTitle: 'Aset Liquid', addLiquid: 'Tambah Aset Liquid', editLiquid: 'Edit Aset Liquid',
    name: 'Nama', nameHint: 'Nama / Keterangan', amount: 'Jumlah', totalCash: 'Total Kas',
    jhtTitle: 'JHT — BPJS Ketenagakerjaan', jhtSub: 'Update manual setiap ada perubahan saldo',
    // Categories
    pasar_uang: 'Pasar Uang', obligasi: 'Obligasi', saham: 'Saham',
    main_pocket: 'Main Pocket', dana_darurat: 'Dana Darurat', lainnya: 'Lainnya',
    // Toast
    toastSaved: 'Berhasil disimpan', toastAdded: 'Berhasil ditambahkan',
    toastDeleted: 'Berhasil dihapus', toastUpdated: 'Berhasil diperbarui',
    // Validation
    errName: 'Nama aset tidak boleh kosong', errBalance: 'Saldo modal harus lebih dari 0',
    errActual: 'Nilai aktual tidak boleh negatif', errSymbol: 'Symbol tidak boleh kosong',
    errNoRate: 'Rate USDT/IDR belum tersedia. Klik Refresh rate dulu.',
    errSaldoUsdt: 'Saldo modal harus lebih dari 0 USDT',
    errAktualUsdt: 'Nilai aktual tidak boleh kosong atau negatif',
    errNama: 'Nama tidak boleh kosong', errJumlah: 'Jumlah harus lebih dari 0',
    errBuyPrice: 'Harga beli harus lebih dari 0', errJhtNeg: 'Jumlah tidak boleh negatif',
    // Vehicle Service
    svcTitle: 'Service Kendaraan', svcAddVehicle: '+ Kendaraan',
    svcKmNow: 'KM Sekarang', svcKmUpdate: 'Klik untuk update KM',
    svcEditVehicle: 'Edit kendaraan', svcDeleteVehicle: 'Hapus kendaraan',
    svcAlertOverdue: 'Servis Terlambat!', svcAlertOverdueSub: 'sudah melewati interval — segera servis.',
    svcAlertDue: 'Jadwal Servis Mendekat', svcAlertDueSub: 'sudah mendekati batas interval.',
    svcTotalRecords: 'Total Catatan', svcHistorySub: 'riwayat servis',
    svcTotalCost: 'Total Biaya', svcAllService: 'semua servis',
    svcLastService: 'Servis Terakhir', svcNoDataSub: 'belum ada data',
    svcStatusOk: 'OK', svcStatusDue: 'Segera', svcStatusOverdue: 'Terlambat', svcStatusNodata: 'Cek',
    svcNoDataComp: 'Tidak ada data', svcInterval: 'Interval',
    svcSectionHistory: 'Riwayat Servis', svcSearchPlaceholder: 'Cari servis, bengkel…',
    svcAddRecord: '+ Catat Servis', svcTimelineTitle: 'Riwayat Singkat',
    svcThDate: 'Tanggal', svcThKm: 'KM', svcThService: 'Servis', svcThShop: 'Bengkel', svcThCost: 'Biaya',
    svcNoResults: 'Tidak ada hasil pencarian', svcNoRecords: 'Belum ada catatan servis',
    svcFooterRecords: 'catatan', svcFooterFrom: 'dari', svcFooterTotal: 'total',
    svcNoVehicles: 'Belum ada kendaraan. Klik "+ Kendaraan" untuk menambahkan.',
    svcHistoryTitle: 'History', svcSearchShort: 'Cari…', svcNoHistory: 'Belum ada history',
    svcNoResults2: 'Tidak ada hasil',
    svcKmUpdated: 'KM diperbarui', svcRecordDeleted: 'Catatan dihapus', svcVehicleDeleted: 'Kendaraan dihapus',
    svcConfirmDeleteVehicle: 'Hapus kendaraan ini? Semua riwayat servisnya juga akan dihapus.',
    svcEditVehicleTitle: 'Edit Kendaraan', svcAddVehicleTitle: '+ Tambah Kendaraan',
    svcErrNamePlate: 'Nama dan plat nomor wajib diisi',
    svcVehicleUpdated: 'Kendaraan diperbarui', svcVehicleAdded: 'Kendaraan ditambahkan!',
    svcLabelName: 'Nama Kendaraan', svcLabelType: 'Jenis', svcLabelPlate: 'Plat Nomor',
    svcLabelYear: 'Tahun', svcPartsTitle: 'Interval Ganti Sparepart',
    svcEditRecordTitle: 'Edit Catatan Servis', svcAddRecordFor: '+ Catat Servis —',
    svcErrDate: 'Tanggal wajib diisi', svcErrMinItem: 'Minimal satu item servis harus diisi',
    svcRecordUpdated: 'Catatan diperbarui', svcServiceRecorded: 'Servis dicatat!',
    svcLabelDate: 'Tanggal Servis', svcLabelKmAtService: 'KM Saat Servis',
    svcLabelShop: 'Bengkel', svcLabelItems: 'Item Servis',
    svcAddItem: '+ Item', svcItemName: 'Nama produk / jenis servis', svcItemCost: 'Biaya',
    svcCompOil: 'Oli Mesin', svcCompFinalDrive: 'Oli Final Drive',
    svcHoursAgo: 'h lalu', svcNext: 'Next', svcDays: 'hari',
    // Mountain Hiking
    hikeTitle: 'Mountain Hiking', hikeAddBtn: '+ Catat Pendakian',
    hikeTotalHikes: 'Total Pendakian', hikeMountainsSub: 'gunung didaki',
    hikeSummitSuccess: 'Summit Berhasil', hikeSuccessRate: 'success rate',
    hikeHighest: 'Tertinggi Didaki', hikeElevationUnit: 'mdpl',
    hikeCitiesVisited: 'Kota / Lokasi', hikeCitiesSub: 'kota berbeda',
    hikeLogTitle: 'Log Pendakian', hikeRecords: 'pendakian',
    hikeEmpty: 'Belum ada catatan pendakian',
    hikeEmptySub: 'Yuk mulai catat gunung pertama yang kamu daki!',
    hikeAddFirst: '+ Catat Pendakian Pertama',
    hikeThMountain: 'Gunung', hikeThDate: 'Tanggal', hikeThDuration: 'Durasi', hikeThStatus: 'Status',
    hikeEditTitle: 'Edit Pendakian', hikeAddTitle: '+ Catat Pendakian Baru',
    hikeLabelMountain: 'Nama Gunung', hikeLabelElevation: 'Ketinggian (mdpl)',
    hikeLabelCity: 'Kota / Lokasi', hikeLabelTrail: 'Jalur / Basecamp',
    hikeLabelStartDate: 'Tanggal Berangkat', hikeLabelEndDate: 'Tanggal Pulang',
    hikeLabelStatus: 'Status Pendakian', hikeLabelPhotos: 'Link Google Photos Album (opsional)',
    hikePhotosHint: 'Paste link album Google Photos untuk akses cepat dari kartu gunung',
    hikePhotosPlaceholder: 'https://photos.google.com/album/…',
    hikeStatusSummit: 'Summit', hikeStatusKawah: 'Kawah', hikeStatusCamp: 'Camp saja', hikeStatusFailed: 'Tidak berhasil',
    hikeDeletedToast: 'Catatan dihapus',
    // Itinerary
    itinTitle: 'Itinerary', itinAddTrip: '+ Trip Baru',
    itinStatDone: 'Trip Selesai', itinStatDays: 'Hari Perjalanan',
    itinStatBudget: 'Total Budget', itinStatAvg: 'Avg Biaya/Trip',
    itinStatTotalTrips: 'total trip', itinStatTotalDays: 'total hari',
    itinStatEstimate: 'estimasi', itinStatPerPerson: 'per orang',
    itinMyTrips: 'Perjalananku',
    itinOngoing: 'Ongoing', itinUpcoming: 'Upcoming',
    itinEmptyTitle: 'Belum ada perjalanan aktif', itinEmptySub: 'Yuk mulai trip baru!',
    itinMilestones: 'Milestone Perjalanan',
    itinNoDone: 'Belum ada trip selesai',
    itinTripDeleted: 'Trip dihapus',
    itinEditTitle: 'Edit Trip', itinAddTitle: '+ Trip Baru',
    itinLabelDest: 'Destinasi', itinLabelPeople: 'Jumlah orang',
    itinLabelStartDate: 'Tanggal Mulai', itinLabelEndDate: 'Tanggal Selesai',
    itinLabelActivities: 'Aktivitas', itinAddActivity: '+ Tambah Aktivitas',
    itinCopied: 'Itinerary disalin ke clipboard!',
    itinCopy: 'Salin', itinDaysLeft: 'hari lagi', itinToday: 'Hari ini!', itinDaysAgo: 'hari lalu',
    itinViewDetail: 'Lihat detail →', itinBudgetCat: 'Budget per Kategori',
    itinThDate: 'Tanggal', itinThTime: 'Jam', itinThActivity: 'Aktivitas',
    itinThLocation: 'Lokasi', itinThPrice: 'Harga/orang', itinThTotal: 'Total',
    itinThStatus: 'Status', itinNoActivities: 'Belum ada detail aktivitas',
    itinUploadFailed: 'Upload gagal',
    itinStatusUpcoming: 'Belum Selesai', itinStatusOngoing: 'Berlangsung',
    itinStatusDone: 'Selesai', itinStatusCancelled: 'Batal', itinStatusOptional: 'Opsional',
    itinErrDest: 'Destinasi wajib diisi',
    // Wedding Planner
    wpTitle: 'Wedding Planner',
    wpTotalBudget: 'Total Budget', wpTotalPaid: 'Sudah Dibayar', wpRemaining: 'Sisa Budget',
    wpOnTrack: 'On Track', wpOverBudget: 'Over Budget', wpNearLimit: 'Hampir', wpNoData: 'Belum Ada',
    wpProgress: '% terpakai', wpOver: '⚠ Over Budget', wpTrack: '✓ On Track',
    wpBudgetCat: 'Budget Categories', wpSetupAll: 'Setup Semua', wpAddCat: '+ Kategori',
    wpAddPayment: '+ Pembayaran', wpCategory: 'Kategori', wpVendor: 'Vendor',
    wpMaxBudget: 'Budget Max', wpEstimate: 'Estimasi', wpPaid: 'Dibayar',
    wpDiff: 'Selisih', wpStatus: 'Status',
    wpRecentActivity: 'Aktivitas Terbaru', wpPayHistory: 'Riwayat Pembayaran',
    wpAddPay: '+ Bayar', wpNoPay: 'Belum ada pembayaran tercatat',
    wpSelectedVendor: 'Vendor Dipilih', wpNoVendor: 'Belum ada vendor dipilih',
    wpChangeVendor: 'Ganti', wpPickVendor: 'Pilih', wpSelectVendorBtn: 'Pilih Vendor',
    wpConfirmVendor: 'Ya, Gunakan Vendor Ini', wpAddNewVendor: '+ Tambah Vendor Baru',
    wpAddVendorTitle: 'Tambah Vendor Baru', wpVendorName: 'Nama Vendor',
    wpPriceEst: 'Estimasi Harga (Rp)', wpBack: 'Kembali',
    wpSetupTitle: 'Setup Budget Kategori',
    wpSetupHint: 'Isi Budget Maks untuk setiap kategori. Kosongkan untuk skip.',
    wpAddCatTitle: 'Tambah Kategori', wpEditCatTitle: 'Edit Kategori',
    wpMaxBudgetLabel: 'Budget Maksimal (Rp)', wpEstimateLabel: 'Estimasi (Rp)',
    wpEditBudget: 'Edit', wpSetGlobalBudget: 'set global budget',
    wpGlobalBudget: 'budget global', wpVendorsReg: 'vendor terdaftar',
    wpTransactions: 'transaksi', wpActiveCats: 'kategori aktif',
    wpRemainSub: 'tersisa', wpOverSub: '⚠ over budget!',
    wpAddCatBtn: 'Tambah Kategori', wpSelectCat: 'Pilih Kategori',
    wpPickVendorFor: 'Pilih Vendor —', wpGunakanVendor: 'Gunakan',
    wpEstAutoFilled: 'Estimasi akan diisi otomatis',
    wpNoVendorCat: 'Belum ada vendor untuk kategori ini',
    wpEmptyTitle: 'Belum ada data wedding 👀',
    wpEmptySub: 'Rencanakan pernikahan impianmu. Catat setiap kategori, vendor, dan pembayaran di satu tempat.',
    wpOneCategory: '+ Satu Kategori', wpSetupAllBtn: 'Setup Semua Kategori',
    wpErrMinOne: 'Isi minimal 1 budget kategori', wpErrBudgetNum: 'Budget harus angka',
    wpErrMaxBudget: 'Budget maksimal wajib diisi', wpErrBudgetAngka: 'Budget maksimal harus angka',
    wpErrPilihKat: 'Pilih kategori', wpErrJumlah: 'Jumlah pembayaran wajib diisi',
    wpErrJumlahNum: 'Jumlah harus berupa angka', wpErrTanggal: 'Tanggal wajib diisi',
    wpSavedCats: 'kategori berhasil disimpan', wpCatAdded: 'Kategori ditambahkan',
    wpCatUpdated: 'Kategori diperbarui', wpCatDeleted: 'Item dihapus',
    wpPayAdded: 'Pembayaran dicatat', wpPayUpdated: 'Pembayaran diperbarui', wpPayDeleted: 'Transaksi dihapus',
    wpVendorPicked: 'dipilih', wpBudgetSaved: 'Total budget disimpan',
    wpConfirmDeleteItem: 'Hapus budget item ini? Semua transaksi terkait juga akan dihapus.',
    wpConfirmDeleteTx: 'Hapus transaksi ini?',
    wpTipePayment: 'Tipe Pembayaran', wpTanggal: 'Tanggal',
    wpTotalBudgetLabel: 'Total Budget', wpGlobalBudgetSet: 'budget global',
    wpErrDupCat: 'Ada nama kategori yang duplikat',
    wpSetupSaved: 'Setup berhasil disimpan',
    wpGlobalBudgetHint: 'Budget global pernikahan — dasar perhitungan sisa keseluruhan',
    wpDeleteWarning: 'kategori akan dihapus beserta semua transaksinya. Klik ↩ untuk batalkan.',
    wpErrVendorName: 'Nama vendor wajib diisi',
  },
  en: {
    logout: 'Logout', loading: 'Loading...',
    add: '+ Add', edit: 'Edit', save: 'Save', saving: 'Saving...',
    cancel: 'Cancel', update: 'Update', updating: 'Saving...',
    delete: 'Yes, Delete', deleting: 'Deleting...',
    refresh: '↻ Refresh',
    total: 'Total', noData: 'No data yet',
    notes: 'Notes', optional: 'Optional', category: 'Category',
    confirmDeleteTitle: 'Delete this item?', confirmDeleteSub: 'This action cannot be undone.',
    portfolioSummary: 'Portfolio Summary', totalAsset: 'Total Assets',
    target: 'Target', fromTarget: 'of target',
    liquidAsset: 'Liquid Assets', nonLiquidAsset: 'Non-Liquid Assets',
    physicalAsset: 'Physical Assets', assetAllocation: 'Asset Allocation',
    nonLiquid: 'Non-Liquid', liquid: 'Liquid', physical: 'Physical',
    totalBuyPrice: 'Total Purchase Value', items: 'items', positions: 'pos',
    bibitTitle: 'BIBIT — Mutual Funds & Bonds',
    addBibit: 'Add BIBIT Asset', editBibit: 'Edit BIBIT Asset',
    assetName: 'Asset Name', balance: 'Balance', balanceLabel: 'Balance (Principal)',
    actual: 'Current', actualLabel: 'Current Value', pnl: 'PnL',
    profitRank: 'Top Profit', topProfitSub: 'Ranked by highest % return',
    binanceTitle: 'Binance — Crypto Portfolio',
    addCrypto: 'Add Crypto', editCrypto: 'Edit Crypto',
    symbol: 'Symbol', balanceIdr: 'Balance (IDR)', actualIdr: 'Current (IDR)',
    actualUsdt: 'Current (USDT)', currentRate: 'Current rate',
    loadingRate: 'Loading...', updatedAt: 'updated',
    balanceUsdt: 'Balance (USDT)', actualNowUsdt: 'Current Value (USDT)',
    physicalTitle: 'Physical Assets', addPhysical: 'Add Physical Asset', editPhysical: 'Edit Physical Asset',
    buyPrice: 'Purchase Price', buyDate: 'Purchase Date', age: 'Age', pricePerMonth: 'Price/Month',
    efficiencyRank: 'Efficiency Ranking', lowestCostSub: 'Lowest price/month = most efficient',
    addDateHint: 'Add purchase date\nto see ranking',
    liquidTitle: 'Liquid Assets', addLiquid: 'Add Liquid Asset', editLiquid: 'Edit Liquid Asset',
    name: 'Name', nameHint: 'Name / Description', amount: 'Amount', totalCash: 'Total Cash',
    jhtTitle: 'JHT — Employment Insurance', jhtSub: 'Update manually when balance changes',
    pasar_uang: 'Money Market', obligasi: 'Bonds', saham: 'Stocks',
    main_pocket: 'Main Pocket', dana_darurat: 'Emergency Fund', lainnya: 'Others',
    toastSaved: 'Saved successfully', toastAdded: 'Added successfully',
    toastDeleted: 'Deleted successfully', toastUpdated: 'Updated successfully',
    errName: 'Asset name cannot be empty', errBalance: 'Balance must be greater than 0',
    errActual: 'Current value cannot be negative', errSymbol: 'Symbol cannot be empty',
    errNoRate: 'USDT/IDR rate not available. Click Refresh rate first.',
    errSaldoUsdt: 'Balance must be greater than 0 USDT',
    errAktualUsdt: 'Current value cannot be empty or negative',
    errNama: 'Name cannot be empty', errJumlah: 'Amount must be greater than 0',
    errBuyPrice: 'Purchase price must be greater than 0', errJhtNeg: 'Amount cannot be negative',
    // Vehicle Service
    svcTitle: 'Vehicle Service', svcAddVehicle: '+ Vehicle',
    svcKmNow: 'Current KM', svcKmUpdate: 'Click to update KM',
    svcEditVehicle: 'Edit vehicle', svcDeleteVehicle: 'Delete vehicle',
    svcAlertOverdue: 'Service Overdue!', svcAlertOverdueSub: 'has exceeded interval — service now.',
    svcAlertDue: 'Service Due Soon', svcAlertDueSub: 'is approaching service interval.',
    svcTotalRecords: 'Total Records', svcHistorySub: 'service history',
    svcTotalCost: 'Total Cost', svcAllService: 'all services',
    svcLastService: 'Last Service', svcNoDataSub: 'no data yet',
    svcStatusOk: 'OK', svcStatusDue: 'Due', svcStatusOverdue: 'Overdue', svcStatusNodata: 'Check',
    svcNoDataComp: 'No data', svcInterval: 'Interval',
    svcSectionHistory: 'Service History', svcSearchPlaceholder: 'Search service, shop…',
    svcAddRecord: '+ Log Service', svcTimelineTitle: 'Recent Timeline',
    svcThDate: 'Date', svcThKm: 'KM', svcThService: 'Service', svcThShop: 'Shop', svcThCost: 'Cost',
    svcNoResults: 'No search results', svcNoRecords: 'No service records yet',
    svcFooterRecords: 'records', svcFooterFrom: 'of', svcFooterTotal: 'total',
    svcNoVehicles: 'No vehicles yet. Click "+ Vehicle" to add one.',
    svcHistoryTitle: 'History', svcSearchShort: 'Search…', svcNoHistory: 'No history for',
    svcNoResults2: 'No results',
    svcKmUpdated: 'KM updated', svcRecordDeleted: 'Record deleted', svcVehicleDeleted: 'Vehicle deleted',
    svcConfirmDeleteVehicle: 'Delete this vehicle? All service records will also be deleted.',
    svcEditVehicleTitle: 'Edit Vehicle', svcAddVehicleTitle: '+ Add Vehicle',
    svcErrNamePlate: 'Name and license plate are required',
    svcVehicleUpdated: 'Vehicle updated', svcVehicleAdded: 'Vehicle added!',
    svcLabelName: 'Vehicle Name', svcLabelType: 'Type', svcLabelPlate: 'License Plate',
    svcLabelYear: 'Year', svcPartsTitle: 'Parts Replacement Interval',
    svcEditRecordTitle: 'Edit Service Record', svcAddRecordFor: '+ Log Service —',
    svcErrDate: 'Date is required', svcErrMinItem: 'At least one service item is required',
    svcRecordUpdated: 'Record updated', svcServiceRecorded: 'Service logged!',
    svcLabelDate: 'Service Date', svcLabelKmAtService: 'KM at Service',
    svcLabelShop: 'Shop', svcLabelItems: 'Service Items',
    svcAddItem: '+ Item', svcItemName: 'Product / service type', svcItemCost: 'Cost',
    svcCompOil: 'Engine Oil', svcCompFinalDrive: 'Final Drive Oil',
    svcHoursAgo: 'd ago', svcNext: 'Next', svcDays: 'days',
    // Mountain Hiking
    hikeTitle: 'Mountain Hiking', hikeAddBtn: '+ Log Hike',
    hikeTotalHikes: 'Total Hikes', hikeMountainsSub: 'mountains climbed',
    hikeSummitSuccess: 'Successful Summits', hikeSuccessRate: 'success rate',
    hikeHighest: 'Highest Peak', hikeElevationUnit: 'masl',
    hikeCitiesVisited: 'Cities Visited', hikeCitiesSub: 'different cities',
    hikeLogTitle: 'Hiking Log', hikeRecords: 'hikes',
    hikeEmpty: 'No hike records yet',
    hikeEmptySub: 'Start logging the first mountain you climbed!',
    hikeAddFirst: '+ Log First Hike',
    hikeThMountain: 'Mountain', hikeThDate: 'Date', hikeThDuration: 'Duration', hikeThStatus: 'Status',
    hikeEditTitle: 'Edit Hike', hikeAddTitle: '+ Log New Hike',
    hikeLabelMountain: 'Mountain Name', hikeLabelElevation: 'Elevation (masl)',
    hikeLabelCity: 'City / Location', hikeLabelTrail: 'Trail / Basecamp',
    hikeLabelStartDate: 'Departure Date', hikeLabelEndDate: 'Return Date',
    hikeLabelStatus: 'Hike Status', hikeLabelPhotos: 'Google Photos Album Link (optional)',
    hikePhotosHint: 'Paste Google Photos album link for quick access from hike card',
    hikePhotosPlaceholder: 'https://photos.google.com/album/…',
    hikeStatusSummit: 'Summit', hikeStatusKawah: 'Crater', hikeStatusCamp: 'Camp only', hikeStatusFailed: 'Did not summit',
    hikeDeletedToast: 'Record deleted',
    // Itinerary
    itinTitle: 'Itinerary', itinAddTrip: '+ New Trip',
    itinStatDone: 'Trips Done', itinStatDays: 'Days Traveled',
    itinStatBudget: 'Total Budget', itinStatAvg: 'Avg Cost/Trip',
    itinStatTotalTrips: 'total trips', itinStatTotalDays: 'total days',
    itinStatEstimate: 'estimated', itinStatPerPerson: 'per person',
    itinMyTrips: 'My Trips',
    itinOngoing: 'Ongoing', itinUpcoming: 'Upcoming',
    itinEmptyTitle: 'No active trips', itinEmptySub: 'Start a new trip!',
    itinMilestones: 'Trip Milestones',
    itinNoDone: 'No completed trips yet',
    itinTripDeleted: 'Trip deleted',
    itinEditTitle: 'Edit Trip', itinAddTitle: '+ New Trip',
    itinLabelDest: 'Destination', itinLabelPeople: 'Number of people',
    itinLabelStartDate: 'Start Date', itinLabelEndDate: 'End Date',
    itinLabelActivities: 'Activities', itinAddActivity: '+ Add Activity',
    itinCopied: 'Itinerary copied to clipboard!',
    itinCopy: 'Copy', itinDaysLeft: 'days left', itinToday: 'Today!', itinDaysAgo: 'days ago',
    itinViewDetail: 'View detail →', itinBudgetCat: 'Budget by Category',
    itinThDate: 'Date', itinThTime: 'Time', itinThActivity: 'Activity',
    itinThLocation: 'Location', itinThPrice: 'Price/person', itinThTotal: 'Total',
    itinThStatus: 'Status', itinNoActivities: 'No activity details yet',
    itinUploadFailed: 'Upload failed',
    itinStatusUpcoming: 'Upcoming', itinStatusOngoing: 'Ongoing',
    itinStatusDone: 'Done', itinStatusCancelled: 'Cancelled', itinStatusOptional: 'Optional',
    itinErrDest: 'Destination is required',
    // Wedding Planner
    wpTitle: 'Wedding Planner',
    wpTotalBudget: 'Total Budget', wpTotalPaid: 'Total Paid', wpRemaining: 'Remaining',
    wpOnTrack: 'On Track', wpOverBudget: 'Over Budget', wpNearLimit: 'Near Limit', wpNoData: 'No Data',
    wpProgress: '% used', wpOver: '⚠ Over Budget', wpTrack: '✓ On Track',
    wpBudgetCat: 'Budget Categories', wpSetupAll: 'Setup All', wpAddCat: '+ Category',
    wpAddPayment: '+ Payment', wpCategory: 'Category', wpVendor: 'Vendor',
    wpMaxBudget: 'Max Budget', wpEstimate: 'Estimate', wpPaid: 'Paid',
    wpDiff: 'Difference', wpStatus: 'Status',
    wpRecentActivity: 'Recent Activity', wpPayHistory: 'Payment History',
    wpAddPay: '+ Pay', wpNoPay: 'No payments recorded',
    wpSelectedVendor: 'Selected Vendor', wpNoVendor: 'No vendor selected',
    wpChangeVendor: 'Change', wpPickVendor: 'Pick', wpSelectVendorBtn: 'Select Vendor',
    wpConfirmVendor: 'Yes, Use This Vendor', wpAddNewVendor: '+ Add New Vendor',
    wpAddVendorTitle: 'Add New Vendor', wpVendorName: 'Vendor Name',
    wpPriceEst: 'Price Estimate (IDR)', wpBack: 'Back',
    wpSetupTitle: 'Setup Category Budget',
    wpSetupHint: 'Enter max budget for each category. Leave blank to skip.',
    wpAddCatTitle: 'Add Category', wpEditCatTitle: 'Edit Category',
    wpMaxBudgetLabel: 'Max Budget (IDR)', wpEstimateLabel: 'Estimate (IDR)',
    wpEditBudget: 'Edit', wpSetGlobalBudget: 'set global budget',
    wpGlobalBudget: 'global budget', wpVendorsReg: 'vendors registered',
    wpTransactions: 'transactions', wpActiveCats: 'active categories',
    wpRemainSub: 'remaining', wpOverSub: '⚠ over budget!',
    wpAddCatBtn: 'Add Category', wpSelectCat: 'Select Category',
    wpPickVendorFor: 'Select Vendor —', wpGunakanVendor: 'Use',
    wpEstAutoFilled: 'Estimate will be auto-filled',
    wpNoVendorCat: 'No vendors for this category',
    wpEmptyTitle: 'No wedding data yet 👀',
    wpEmptySub: 'Plan your dream wedding. Track every category, vendor, and payment in one place.',
    wpOneCategory: '+ One Category', wpSetupAllBtn: 'Setup All Categories',
    wpErrMinOne: 'Fill at least 1 category budget', wpErrBudgetNum: 'Budget must be a number',
    wpErrMaxBudget: 'Max budget is required', wpErrBudgetAngka: 'Max budget must be a number',
    wpErrPilihKat: 'Select a category', wpErrJumlah: 'Payment amount is required',
    wpErrJumlahNum: 'Amount must be a number', wpErrTanggal: 'Date is required',
    wpSavedCats: 'categories saved', wpCatAdded: 'Category added',
    wpCatUpdated: 'Category updated', wpCatDeleted: 'Item deleted',
    wpPayAdded: 'Payment recorded', wpPayUpdated: 'Payment updated', wpPayDeleted: 'Transaction deleted',
    wpVendorPicked: 'selected', wpBudgetSaved: 'Total budget saved',
    wpConfirmDeleteItem: 'Delete this budget item? All related transactions will also be deleted.',
    wpConfirmDeleteTx: 'Delete this transaction?',
    wpTipePayment: 'Payment Type', wpTanggal: 'Date',
    wpTotalBudgetLabel: 'Total Budget', wpGlobalBudgetSet: 'global budget',
    wpErrDupCat: 'Duplicate category names found',
    wpSetupSaved: 'Setup saved successfully',
    wpGlobalBudgetHint: 'Global wedding budget — basis for remaining balance calculation',
    wpDeleteWarning: 'categories will be deleted along with all their transactions. Click ↩ to undo.',
    wpErrVendorName: 'Vendor name is required',
  }
}
